python -m torch.distributed.launch --nproc_per_node 1 main.py \
--train_data_path data/dataset_emoji_train_data.csv \
--val_data_path data/dataset_emoji_val_data.csv \
--test_data_path data/dataset_emoji_test_data.csv \
--model Roberta \
--gpus 1 \
--lr 3e-5 \
--epochs 5 \
--batch_size 512 \
--noise RPN \
--prob 0.3 \
--adv_step 3